name: Python Unit Tests

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12  # Choose the Python version you need for your tests

    - name: Start Docker Compose
      run: docker-compose up -d db_sql

    - name: Wait for database to start
      run: |
        while ! nc -z localhost 5432; do sleep 1; done
        echo "Database is up and running!"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements file for your tests

    - name: Run tests db
      run: ./BackEnd/internal/database/test/bd_unittest.py  # Or the command to run your unit tests

    - name: Stop Docker Compose
      run: docker-compose down
